spring:
  application:
    name: product-ui

server:
  port: 8081

management:
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
